### ISSUE TITLE
[Feature Request] `!psn check updates` Improvements

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/discord-bot#180]
Example usage: `!psn check updates ni no kuni`

In order to avoid having to implement a whole search / fuzzy search functionality over the metadata db, this should / could be done via asking :b:Ani's api for compat list in regards to the query string, extract the first matching titleID, and pipe it to the currently used function.

Maybe the bot should also echo some info onto discord along with the found updates, like:
`Showing updates for Ni no Kuni - Wrath of the White Witch [BLUS30947].`
`If this isn't the list of updates you were looking for, please use a titleID instead.`

When implemented, the explanation of the command should also be updated with the freshly added syntax.

**Update:** I'm a dumdum, and forgot that there are multiple titleIDs for each game smh. I should go back to rpcs3 school quick.

Anyways, this would also entail that if you use a game title as your query, you'd get results for all the regions and mediatypes the given game has been released in. This does mean that the resulting list _will_ be pretty long, though I'm fairly sure the command is already limited to #bot-spam, making this less of an issue.

Auto-limiting to one region & media format could maybe applied when the list is too big. (see Gran Turismo games)

Extra specifiers could maybe added as well, not sure how to go about them. They could help filtering the possible titleIDs, by forcing a region (e,g. eu, usa, etc.) and optionally a mediatype (disc/digital).

Example: `!psn check updates eu disc tlou`.

All in all, needs a bit more brainstorming, but I think the general idea is definitely nice, and more galaxybrain user-friendly too.

**Comment by 13xforever** [comment]
updates are product-code specific, doing lookups by name won't work without much complication on the bot side _and_ in query syntax, so it will be more misery without much gain in my opinion

**Comment by nitrohigito** [comment]
> updates are product-code specific, doing lookups [will be hard]

I'm aware, see the part after `Update:`. I do see why you might think it doesn't worth the added effort though.

Regardless, if you decide to roll with it, the real issue here is when the ambiguity results in a huge list. This means that maybe switching to compatbot-style listings will be necessary, at least in the case of these title-based lookups.
