### ISSUE TITLE
Issues with bot reaction matching

### ISSUE THREAD

**Issue by JohnHolmesII** [RPCS3/discord-bot#193]
Some fuzzy matching rules seem to be applied to areas that really don't need it, leading to oddities. In particular, the bot will assume it is being discussed if anyone uses any word beginning with "bot", regardless of the word itself, including "bothered" or even "botasdf".

Test case "great botasdf"

In any case, this really just highlights that there should only be a subset of keywords to which fuzzy matching is applied. Cheers m8.

**Comment by 13xforever** [comment]
there's no fuzzy matching in that handler, only some tentative substring lookups, and it works as intended most of the time

even when it sometimes reacts unintentionally, it's still fine as bot just thinks you were nice, and everyone likes when bot likes them

I'm not sure making it _perfect_ would be _better_ from the fun side

**Comment by JohnHolmesII** [comment]
Good to hear it's not fuzzy matching. That makes the whole thing much simpler. Just add a space or punctuation to the search string.

It's not about making it perfect at all, it's just that the 2 paragraphs I posted had nothing even remotely to do with the bot. It wasn't fun, it was just odd.

Importantly, nothing is stopping the bot from using its negative reactions either, which would be far more confusing.

Remember, this collision happened in reality, and confused the people who saw it happen. Not everything comes across as a charming accident.
