### ISSUE TITLE
An ability to force username changes by admins

### ISSUE THREAD

**Issue by 13xforever** [RPCS3/discord-bot#249]
Some people are really annoying and try to change their usernames to break the rule about the diacritics vomit. Usually they get a kick, but sometimes they return, or mods are unavailable.

It would be useful to keep a list of such users and force the specified username at all times.

**Comment by Laxynium** [comment]
Hi, I would like to start working on that issue. Could you provide more details, because I am not sure what are those rules about the diacritics vomit?

**Comment by 13xforever** [comment]
Sure

**Comment by 13xforever** [comment]
This issue is purely to add an ability to force a specific username to a specific user, you don't need to check anything special. Just a monitor and a periodic check that the server nickname is set to what mods defined.

**Comment by 13xforever** [comment]
Fixed by #447
