### ISSUE TITLE
Abuse Rich Presence for basic information displayment

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/discord-bot#282]
Recently noticed how Rich Presence is sometimes abused with bots, so they can display the default help command and a link to their site / repository:

e.g. `Use !help for more information. | https://github.com/RPCS3/discord-bot/`

**Comment by 13xforever** [comment]
Rich Presence is not covered by Discord API that is exposed to bots, and requires a separate library. I looked into this not too long ago.

Most popular seems to be [Discord RPC](https://github.com/Lachee/discord-rpc-csharp). I just need some time to read up on docs and the library API.

**Comment by nitrohigito** [comment]
Sounds cool, thanks.
