### ISSUE TITLE
[Idea/Entertainment] Rate command

### ISSUE THREAD

**Issue by MsDarkLow** [RPCS3/discord-bot#49]
A command for entertainment just like !8ball

Add a command "rate", example:
- Me: !rate loweys
- Bot: Baaaaaaaaaaaaaaaad

The bot will randomly rate anything you have written in front of it.

With a bonus if someone rates something specifically, you'll get a specific answer too like
"!rate Nekotekina" "Russian Kot is supreme amazing"

Idunno. Take your time™
~~May Yakuza guide thee~~

**Comment by Megamouse** [comment]
![image](https://user-images.githubusercontent.com/23019877/42598028-1fc2dca8-855b-11e8-9a59-e0b3c36d5268.png)
🤔

**Comment by MsDarkLow** [comment]
Something wrong ain't right

**Comment by 13xforever** [comment]
[Response list](https://github.com/RPCS3/discord-bot/files/2199515/new_6.txt) from MsDarkLow so I won't forget where I put it again
