### ISSUE TITLE
[Feature Request] Let compatbot highlight if the user uses an outdated build

### ISSUE THREAD

**Issue by nitrohigito** [RPCS3/discord-bot#50]
The idea is that when a user uploads their log, the compatbot would use some visual clues to highlight to both the user and the helpers, that an outdated RPCS3 build is being used.

The bot doesn't actually have to check if the build is outdated or not (since there's no proper build numbering), only if the build number matches with the one found in something like the !latest.

**Comment by JohnHolmesII** [comment]
Just use Bani's api to get the current master

**Comment by nitrohigito** [comment]
that's what i advised first on discord too
lit if good
