### ISSUE TITLE
[Feature Request] Mention if a user is using a known broken build

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/discord-bot#546]
Title is self-explanatory. Obvious limitations are:
- not knowing until how long builds are broken for
- bad builds wont be tagged immediately

**Comment by 13xforever** [comment]
Build status is not tracked anywhere, and _if_ the bot _will_ start this tracking, it would require reimplementing almost the whole update api

**Comment by HerrHulaHoop** [comment]
This should ideally be tracked in the website's API. That way the auto-updater and discord bot could both pull the info from the same source and alert the users. Not all RPCS3 users are present on discord. Should work with Ani and possibly open an issue on the Compat list repo.

**Comment by dio-gh** [comment]
> Build status is noz tracked anywhere

It is visually noted at least in #build-updates.
