### ISSUE TITLE
Log deleted messages to a hidden channel

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/discord-bot#585]
Received reports about some quite offending messages being posted to #off-topic by a certain user, then quickly deleted. At the PCSX2 discord, the bot logs all deleted messages to a separate hidden staff channel for review. Perhaps it's a good idea?

Possible gotchas:
- the deleted msg could be the same message that got posted afterwards, and the user just wanted the `(edited)` to disappear for clarity reasons
- not sure if (image) spoiler markings can be replicated?
- probably not possible for hidden channels

**Comment by 13xforever** [comment]
idk if it's a good idea to log in a channel, as you can ddos discord api quite easily, I'd opt out for bot logs

and it would require approval from the staff

implementing it is trivial tho

**Comment by dio-gh** [comment]
I'm confused, did this get implemented after all? The title of the linked PR reads like it resolves the issue mentioned in your last paragraph.

> idk if it's a good idea to log in a channel, as you can ddos discord api quite easily
Does this stand for message editing events too? Perhaps if they were batched up, it'd be harder to abuse and exhaust the call limits.

> and it would require approval from the staff
Well yeah, it does.

**Comment by 13xforever** [comment]
shh, everything is fine

**Comment by dio-gh** [comment]
Ok, thanks.
