### ISSUE TITLE
Feature Request: !fortune command

### ISSUE THREAD

**Issue by MsDarkLow** [RPCS3/discord-bot#699]
Add a !fortune command to tell the fortune of the users, just like in fortune cookies!
Example: The harder you work, the luckier you get.
I suggest to make it only usable 1 time per day for each user (or static 12hr, 16hr, 20hr interval).
~~I'll try to come up with a list of sentences/fortunes, I'll edit the issue when I gather them.~~
(on rpcs3 server) Maybe restrict the command to DMs, #bot-spam and #off-topic

Edit: Made a first list for starting with 38 quotes. https://paste.sh/eoQX_jyn#YETGWgErDz_rw7CWaTcy0DiW

**Comment by 13xforever** [comment]
need some source for fortunes

**Comment by MsDarkLow** [comment]
For starters, I searched around 35 quotes, also included the source where I found them https://paste.sh/eoQX_jyn#YETGWgErDz_rw7CWaTcy0DiW

**Comment by 13xforever** [comment]
default linux fortune database: https://github.com/bmc/fortunes/blob/master/fortunes
additional database: https://github.com/ruanyf/fortunes/blob/master/data/fortunes
I think I'll make a mod command to import new quotes in this format
