### ISSUE TITLE
Implement command for viewing filters

### ISSUE THREAD

**Issue by MSuih** [RPCS3/discord-bot#723]
The new command would show the same message as `!piracy edit`, but would not add or listen for reactions that are used for editing the filter.

Syntax could be `!piracy view <id>`

**Comment by 13xforever** [comment]
I have a todo to make `!filters list` to dump everything in a text attachment instead of the messages, so it should take care of the spam, and I don't see how this would be helpful, you can use edit command and not actually edit

**Comment by MSuih** [comment]
That's what I've been doing, but it feels a bit janky especially when the view gets closed once you stop editing. Anyways, the reason I opened this issue is that thought that this was just an oversight and trivial to add. You can colse it if you don't feel like such feature should be added.

**Comment by 13xforever** [comment]
It is trivial to implement, I just don't see how it's useful in any way
