### ISSUE TITLE
Operating system parsing fails

### ISSUE THREAD

**Issue by MSuih** [RPCS3/discord-bot#812]
![unknown](https://user-images.githubusercontent.com/19759300/132133907-5517e29b-4885-40c3-9f1c-fa3e8b4be370.png)
Operating system information should be at the end of firmware string, in format of "Windows 10 20H2" or similar. In this case, it's pasted the output in entirety and also contains lines for Qt version information and vulkan thread being shut down.
[RPCS3.log](https://github.com/RPCS3/discord-bot/files/7111976/RPCS3.log)

**Comment by clienthax** [comment]
I have only seen this happen once, is this still happening?

**Comment by clienthax** [comment]
seems to be the BuildInfoInLog regex fails out on "local_build" versions
