### ISSUE TITLE
PSN Demon's Souls reported as 'Disc game installed as PKG'

### ISSUE THREAD

**Issue by YuriNator557** [RPCS3/discord-bot#816]
After being reported as Playable, instead of just saying 'This version of the game doesn't currently work' it says this instead. 
I understand that this is technically true since the PARAM.SFO is that of the disc version, but is it possible to make an exception for this game as it has piracy connotations (at least according to the bot)?

![image](https://user-images.githubusercontent.com/76178650/134241878-47376e66-304f-4fe4-b4b2-1c9b738cc4e3.png)

**Comment by HerrHulaHoop** [comment]
We don't need to remove the note, just get rid of the emoji and change it to the default Info icon.

If you want you could make the emoji change specifically for DeS but I imagine it'd be easier to change it for all scenarios.
