### ISSUE TITLE
If linux PR build fails, it gets stuck as pending

### ISSUE THREAD

**Issue by MSuih** [RPCS3/discord-bot#829]
When Linux PR build fails, it seems to mark itself as fail for windows build
![image](https://user-images.githubusercontent.com/19759300/143299889-8e6dbaa8-844a-44e2-800a-79d3d1fbae00.png)

When the slower Windows build finishes compiling, it marks itself as success, which overrides the previous failure:
![image](https://user-images.githubusercontent.com/19759300/143299936-048ebf5d-a8f7-4caf-9240-c92c3585ef21.png)

Thus the Linux build will get stuck in pending state

**Comment by clienthax** [comment]
Fixed by https://github.com/RPCS3/discord-bot/pull/837
