### ISSUE TITLE
Support discord.com invite links for whitelisting

### ISSUE THREAD

**Issue by MSuih** [RPCS3/discord-bot#842]
Discord previously used discord.gg domain for invite links. For example, https://discord.gg/Af7H9yp is the old syntax and it now redirects users to https://discord.com/invite/Af7H9yp

When using `!invite whitelist`, bot will only accept old discord.gg invites. Trying to add a discord.com invite will cause it to react with ⛔ . Changing the url manually will work around this issue.

**Comment by clienthax** [comment]
The discord client still generates the discord.gg links, I don't see much point in this currently.

**Comment by 13xforever** [comment]
It's been supported since very beginning, this is invalid issue and may be closed
