### ISSUE TITLE
PSN Demon's Souls still have the message "That game doesn't work"

### ISSUE THREAD

**Issue by Jonathan44062** [RPCS3/discord-bot#847]
Since the PSN version of Demon's Souls is playable, is necessary to remove that message from the bot to avoid some misunderstanding 
![image](https://user-images.githubusercontent.com/78843189/154377035-efc0d1b1-97b0-459e-9337-521c67c6eed1.png)

**Comment by clienthax** [comment]
Is this the same for all games here?
https://github.com/RPCS3/discord-bot/blob/1e93942d3ab91549b2390ed1d545c4a1bab75f72/CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs#L89

**Comment by Jonathan44062** [comment]
Not that I am aware of, the Disc Version of the game doesn't show that message
Just for PSN DeS i guess

**Comment by 13xforever** [comment]
what version of emulator fixed this?

**Comment by Jonathan44062** [comment]
https://github.com/RPCS3/rpcs3/pull/10849 This one
