### ISSUE TITLE
Bot does not recognise Steam Deck configuration when parsing a log

### ISSUE THREAD

**Issue by YuriNator557** [RPCS3/discord-bot#854]
Bot cannot detect CPU, thread count, RAM or the proper version of Linux, just reports it as 'Linux'. GPU is reported OK
[RPCS3 (3).log.gz](https://github.com/RPCS3/discord-bot/files/8357393/RPCS3.3.log.gz)
![image](https://user-images.githubusercontent.com/76178650/160278064-1dc75f6f-59ed-4ced-9eb3-1586a2ab8d8a.png)

**Comment by clienthax** [comment]
Rpcs3 problem, log line is broken
![Screenshot_20220426-231840](https://user-images.githubusercontent.com/1056270/165402523-3452fe5f-ac65-4ae0-9865-c058ecb6656c.jpg)
