### ISSUE TITLE
The Simpsons Game outdated logging

### ISSUE THREAD

**Issue by Satan86** [RPCS3/discord-bot#857]
Hey :) 
The Simpsons game has a log message where it mentions pad initialisation issues and the solution being "Simply unplug and replug it until it works". That message is OutDated, as there is a patch that fixes the issue. Can you change the message to tell people to use the Patch instead?
![image](https://user-images.githubusercontent.com/61447828/164761904-87d0ca53-6fd0-4072-95b1-a49656b8c133.png)

**Comment by clienthax** [comment]
https://github.com/RPCS3/discord-bot/blob/1236068ab8bfb072b0966768513b505fb6f20180/CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs#L696
