### ISSUE TITLE
Gran Turismo 6 wrong settings recommended

### ISSUE THREAD

**Issue by Satan86** [RPCS3/discord-bot#859]
Gran Turismo 6 logs past version 1.05 mention Read Depth Buffer as "might be required", but it should say "Read Colour Buffers is disabled, please enable", and "Write Colour Buffer is disabled, please enable".

**Comment by clienthax** [comment]
Write colour buffer has a note that says it causes flickering currently, still valid or not?

**Comment by YuriNator557** [comment]
It doesn't flicker past 1.05
