### ISSUE TITLE
Linking/Referencing merged PR's should link to old master build when the PR merged rather than latest

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/discord-bot#860]
Currently, when you mention a old PR via URL or `#PRNumber` the download links go to the **latest** master build of RPCS3, instead of the master build when the PR merged.
![image](https://user-images.githubusercontent.com/15137035/167054902-283faba5-becd-41bf-bffb-97c57d4aa2f3.png)
I would like this to change to instead link to the build when the PR merged, and have a warning about how it is an older build. To improve upon this, there could be a link to the master build directly BEFORE the mentioned PR merged. So you could link e.g #11607 and get a link to when the Surface Cache PR merged, and the build directly before it. Saving tons of time searching the build history page.

Closes [#814](https://github.com/RPCS3/discord-bot/issues/814)

**Comment by Darkhost1999** [comment]
![image](https://user-images.githubusercontent.com/60384196/181613391-6cf232d6-84a1-4107-a2d7-ac2a4fe7236b.png)
Still an annoying issue that created problems in help too. I remember this linking to https://api.cirrus-ci.com/v1/artifact/task/4562251708366848/Artifact/rpcs3-v0.0.23-13cec72b_win64.7z or the applicable PR in the past. Maybe thats just me though confusing merged and unmerged PRs

**Comment by 13xforever** [comment]
I don't want randoms looking for old pr numbers to get old builds, so default behavior will stay as it is now.
But in case someone wants to link old build on purpose, I've implemented `!pr link XXX` command that will link old build.
