### ISSUE TITLE
bot log needs to be updated with the proper SPU Xfloat Accuracy levels

### ISSUE THREAD

**Issue by Yahfz** [RPCS3/discord-bot#874]
![image](https://user-images.githubusercontent.com/17715080/177014282-9466a31c-6875-477c-ae0f-a74c70bb3551.png)
this needs to be renamed to show one of the 4 settings. 
Relaxed, approximate, accurate and 'disabled'.

**Comment by Yahfz** [comment]
also, youre gay

**Comment by Jonathan44062** [comment]
Is not related to this https://github.com/RPCS3/discord-bot/issues/858? I give the reference how can the log looks like with the SPU Xfloat
