### ISSUE TITLE
Please update the bot's response for logs with intel ARC GPUs 

### ISSUE THREAD

**Issue by tomatotango** [RPCS3/discord-bot#945]
Currently when someone with an intel ARC GPU uploads a log this (refer to the attached screenshot) is the response they get from the bot. Please update it for ARC GPUs when you can. Thank you. 
<img width="362" alt="arc" src="https://github.com/RPCS3/discord-bot/assets/46571711/28afa64f-1af0-4955-ba9e-aeb75c9babc5">

**Comment by 13xforever** [comment]
where's the sample log? I can't do anything from a screenshot of already formatted embed
