### ISSUE TITLE
Display error on macOS 14.0-14.2 logs if CPU is VirtualApple

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/discord-bot#948]
macOS 14.0 to macOS 14.2 versions have broken Rosetta 2. It was fixed on macOS 14.3

We need the bot to show an error if the log has a VirtualApple CPU (showing we're running under Rosetta 2) as well as macOS between 14.0 and 14.2, including

**Comment by AniLeo** [comment]
We added this as a hard check in the emulator itself, but it might still be useful to have just in case

**Comment by 13xforever** [comment]
Please attach sample logs for testing
